---
title: "Herramientas Cuantitativas para el Análisis Político"
output: 
 #pdf_document: default
 html_document:
  css: "styles.css"
---

#### [CP44] Maestría en Ciencia Política | UNIVERSIDAD TORCUATO DI TELLA | Sep - Nov 2020

---

# PROGRAMA 
**([Descargar](programa.pdf))**

---

**Sesión 1**: Presentación

---

**Sesión 2**: Introducción 

Conociendo R + RStudio

* R base y el suite _Tidyverse_

* Organizar el trabajo (.Rproj, `here` y git)

* Reproducibilidad y Comunicación (.R y Rmd)

---

**Sesión 3**: Domar los datos I

Los principales paquetes y sus verbos para: 

1. leer datos (`readr`, `heaven`, `readxl`, `googlesheets4`, [etc](https://www.tidyverse.org/packages/#import))

2. limpiar datos (`tidyr`, `janitor`, `tibble`)

3. transformar datos (`dplyr`)

---

**Sesión 4**: Domar los datos II

Ampliando la caja de herramientas: 

1. `lubridate` para trabajar el _tiempo_

2. `forcats` para datos categóricos (*factors*)

3. `stringr`para datos de texto 

---

**Sesión 5**: Programación (intro)

Funciones para no repetirse uno mismo

* La pipa de `magrittr` (`%>%`)

* Introducción a `purrr` (programación funcional)

* `glue`para facilitar la concatenación

---

**Sesión 6**: Data Viz I

* _La Gramática de los Gráficos_

* Introducción a `ggplot2`

---

**Sesión 7**: Data Viz II

* Las muchas capas de `ggplot2` 

* Extensiones: `patchwork`, `ggforce`, `ggparliament`, entre otros. 

---

**Sesión 8**: Data Viz III

Distintas formas de representar información geográfica: 

1. `sf`: para mapas estáticos

2. `leaflet`: para mapas interactivos

3. `geofacet`: para _grillas como si fueran mapas_

---

**Sesión 9**: Tópicos I

Descargar datos de la web: ejemplos aplicados con la API de _Twitter_ vía `rtweet` y scraping con `rvest`

---

**Sesión 10**: Tópicos II


Análisis Cuantitativo de Texto: una primera aproximación a `tidytext`, `tm` , `topicmodels` y otros. 

---

**Sesión 11**: Tópicos III

* Herramientas de Comunicación

* Definiciones del trabajo final

---


#  #MétodosCiPol


#### [`r icon::fa("globe")`/MetodosCiPol/](https://tuqmano.github.io/MetodosCiPol/2020)


#### [`r icon::fa("github")`/MetodosCiPol/](https://github.com/TuQmano/MetodosCiPol/2020)



