---
title: "Herramientas Cuantitativas para el Análisis Político"
output: 
 html_document:
  css: "styles.css"
---

#### [CP44] Maestría en Ciencia Política | UNIVERSIDAD TORCUATO DI TELLA | Sep - Nov 2020

---

# DATOS 

### Elecciones, Votaciones Legislativas y Discursos Presidenciales

[{polAr}](https://electorarg.github.io/polAr/): Política Argentina usando `R`. 


### Socio Económicos 

[{eph}](https://holatam.github.io/eph/): Caja de Herramientas para el procesamiento de la Encuesta Permanente de Hogares. 

[{transporteAR}](https://github.com/juanifulponi/transporteAR): Base de datos de subsidios y compensasiones al transporte público de la República Argentina. 

[{PortalHacienda-CRAN}](https://github.com/fmgarciadiaz/PortalHacienda-CRAN): acceso a la API del Portal del Ministerio de Hacienda de Argentina. 

### DD.HH.

[{presentes}](https://diegokoz.github.io/presentes/index.html):  poner a disposición la información oficial sobre víctimas del terrorismo de estado en Argentina. 

### GEO 

[{geofaceteAR}](https://electorarg.github.io/geofaceteAR/):  Códigos geográficos de Argentina y grillas para visulaización de datos _como si fueran mapas_ (una versión ampliada del trabajo con información geográfica fue incorporada recientemente en {polAr}).  

[{gegorefar}](https://github.com/pdelboca/georefar):  paquete de R que implementa un wrapper para la API georef-ar. La API del Servicio de Normalización de Datos Geográficos, permite normalizar y codificar los nombres de unidades territoriales de la Argentina (provincias, departamentos, municipios y localidades) y de sus calles, así como ubicar coordenadas dentro de ellas.  

[{RUMBA}](https://github.com/bitsandbricks/RUMBA):  Un conjunto de herramientas para analizar la Región Urbana Metropolitana de Buenos Aires usando R.  

### R para Ciencia de Datos - Comunidad Ñ 

[{DATOS}](https://cienciadedatos.github.io/datos/): provee la traducción al español de conjuntos de datos en inglés originalmente disponibles en otros paquetes de R. 

[#DatosDeMiercoles](https://github.com/cienciadedatos/datos-de-miercoles): Datos de miércoles es el primo latinoamericano de #tidytuesday, un proyecto semanal de datos organizado por la comunidad de R. 
 

#  #MétodosCiPol

#### [`r icon::fa("globe")`/MetodosCiPol/](https://tuqmano.github.io/MetodosCiPol/)

#### [`r icon::fa("github")`/MetodosCiPol/](https://github.com/TuQmano/MetodosCiPol)



