---
title: "Herramientas Cuantitativas para el Análisis Político"
output: 
 html_document:
  css: "styles.css"
---

```{r global_opts, echo=FALSE}

 knitr::opts_chunk$set(cache = TRUE)

```



#### [CP44] Maestría en Ciencia Política | UNIVERSIDAD TORCUATO DI TELLA | Sep - Nov 2020

---

### MATERIAL

##### -> [BIBLIOGRAFÍA](https://tuqmano.github.io/MetodosCiPol/bibliografia.html)

##### -> [PROGRAMA](https://tuqmano.github.io/MetodosCiPol/programa.html)

##### -> [DATOS](https://tuqmano.github.io/MetodosCiPol/datos.html)

---

### CLASE 1 

* [PRESENTACIÓN](https://tuqmano.github.io/MetodosCiPol/Clase01/Clase1.html) 

* [INSTALACIÓN Y RECURSOS](https://tuqmano.github.io/MetodosCiPol/Clase01/install_soft.html) 


### CLASE 2

* [PRESENTACIÓN](https://tuqmano.github.io/MetodosCiPol/Clase02/Clase2.html) 

#### Machetes 

* [RStudio - Entorno de Desarrollo Integrado (IDE)](https://github.com/rstudio/cheatsheets/blob/master/translations/spanish/rstudio-ide_Spanish_Translation_Monica_Alonso.pdf)  

* [R Markdown para la comunicación](https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)  
* [Comparación de sintaxis: formas de escribir código en `R`](https://github.com/rstudio/cheatsheets/raw/master/translations/spanish/syntax_spanish.pdf)

### CLASE 3

* [PRESENTACIÓN](https://tuqmano.github.io/MetodosCiPol/Clase03/Clase3.html) 

#### Machetes 

* [Importar y Limpiar Datos](https://github.com/rstudio/cheatsheets/raw/master/translations/spanish/data-import-Spanish_translation-2019.pdf)  con `{readr}` y `{tidyr}`

* [Transformar Datos](https://github.com/rstudio/cheatsheets/raw/master/translations/spanish/data-transformation_Spanish.pdf)  con `{dplyr}`


### CLASE 4

* [PRESENTACIÓN](https://tuqmano.github.io/MetodosCiPol/Clase04/Clase4.html) 

#### Machetes 

* [Datos Categóricos (_Factores_)](https://github.com/rstudio/cheatsheets/raw/master/translations/spanish/factors-Spanish.pdf) con `{factors}`

* [Datos de Tiempo (*Fechas y Horas*)](https://github.com/rstudio/cheatsheets/raw/master/translations/spanish/lubridate-Spanish-translation-2019.pdf) con `{lubridate}`

* [Datos de Texto (_Character_)](https://github.com/rstudio/cheatsheets/raw/master/translations/spanish/strings_Spanish.pdf) con `{stringr}`

---

###  #MétodosCiPol

#### [`r icon::fa("globe")`/MetodosCiPol/](https://tuqmano.github.io/MetodosCiPol/)

#### [`r icon::fa("github")`/MetodosCiPol/](https://github.com/TuQmano/MetodosCiPol)





### TuQmano

##### [`r icon::fa("globe")`](https://www.tuqmano.com/) [tuqmano.com](https://www.tuqmano.com/) 
##### [`r icon::fa("twitter")`](https://twitter.com/TuQmano)  [TuQmano](https://twitter.com/TuQmano) 
##### [`r icon::fa("github")`](https://github.com/tuqmano) [TuQmano](https://github.com/tuqmano)


